### ISSUE TITLE
Minor Formatting Issue

### ISSUE THREAD

**Issue by claremboyle** [ucsb-teaching-cs/w21#4]
This might be pedantic and not that important, but I noticed in w21/resources/adding_bio.md under Acknowledgement / Contact Me that the professor's email doesn't include a period between ucsb and edu.

**Comment by ykharitonova** [comment]
What a nice attention to details!

The omission is intentional to throw off the bots, since humans are much better at figuring out that the `edu` needs to be connected to `ucsb` via a `.` :-)
